//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Participantes.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPANTES
    {
        public string REG { get; set; }
        public string COD_PART { get; set; }
        public string NOME { get; set; }
        public string COD_PAIS { get; set; }
        public string CNPJ { get; set; }
        public string CPF { get; set; }
        public string IE { get; set; }
        public string COD_MUN { get; set; }
        public string SUFRAMA { get; set; }
        public string END { get; set; }
        public string NUM { get; set; }
        public string COMPL { get; set; }
        public string BAIRRO { get; set; }
    }
}
